version: "3.8"
name: memo-flash
services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "9000:3000"
  frontend:
    build: ../memo-flash-front
    container_name: frontend
    ports:
      - "8000:5173"
    stdin_open: true
