version: "3.8"
name: memo-flash
services:
  backend:
    build: ./
    container_name: backend
    # mirror port 3000 to new port 9000
    ports:
      - "9000:3000"
    # mirror this path to app folder (docker) except the node_modules
    volumes:
      - ./:/app
      - /app/node_modules

  frontend-dev:
    build: ../memo-flash-front
    container_name: frontend-dev
    ports:
      - "8000:5173"
    volumes:
      - ../memo-flash-front:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:9000/
      - NODE_ENV=development

  frontend-prod:
    build: ../memo-flash-front
    container_name: frontend-prod
    ports:
      - "8100:5173"
    volumes:
      - ../memo-flash-front:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=https://memo-flash-back.vercel.app/
      - NODE_ENV=production